import Link from "next/link";
import { requireAdminRole } from "@/lib/access";
import { createSupabaseServerClient } from "@/infrastructure/supabase/server";
import { formatZar } from "@/lib/money";

type Metrics={successful_tip_count:number;participating_venue_count:number;active_worker_count:number;gross_gratuity_cents:number;swifttip_gross_revenue_cents:number;provider_cost_cents:number;contribution_cents:number;average_gratuity_cents:number;average_contribution_cents:number;transactions_per_active_worker:number;contribution_per_active_worker_cents:number;settlement_record_count:number;successful_settlement_count:number;settlement_success_rate_pct:number;refund_tip_count:number;refund_rate_pct:number;dispute_tip_count:number;dispute_rate_pct:number;support_case_count:number;support_cases_per_100_tips:number};
const zero:Metrics={successful_tip_count:0,participating_venue_count:0,active_worker_count:0,gross_gratuity_cents:0,swifttip_gross_revenue_cents:0,provider_cost_cents:0,contribution_cents:0,average_gratuity_cents:0,average_contribution_cents:0,transactions_per_active_worker:0,contribution_per_active_worker_cents:0,settlement_record_count:0,successful_settlement_count:0,settlement_success_rate_pct:0,refund_tip_count:0,refund_rate_pct:0,dispute_tip_count:0,dispute_rate_pct:0,support_case_count:0,support_cases_per_100_tips:0};
function pct(v:number){return `${Number(v).toFixed(2)}%`;}
function threshold(value:number,target:number,mode:"min"|"max"="min"){const pass=mode==="min"?value>=target:value<=target;return <span className={pass?"status-chip success":"status-chip warning"}>{pass?"Pass":"Watch"}</span>;}

export default async function PilotPage({searchParams}:{searchParams:Promise<{days?:string}>}){
  const access=await requireAdminRole(["operations_admin","finance_admin","super_admin"]);
  const params=await searchParams;
  const requested=Number(params.days??30);
  const days=[7,30,45,90].includes(requested)?requested:30;
  const to=new Date();
  const from=new Date(to.getTime()-days*24*60*60*1000);
  let m=zero;
  if(access.mode==="live"){
    const supabase=await createSupabaseServerClient();
    const {data}=await supabase.rpc("admin_get_pilot_metrics",{p_from:from.toISOString(),p_to:to.toISOString()});
    m=((data??[]) as Metrics[])[0]??zero;
  }
  return <main className="dashboard-shell"><header className="dashboard-topbar"><div><span className="eyebrow">Pilot evidence</span><h1>Commercial and operational scorecard</h1><p className="lead">Derived from canonical Tips, Settlements, provider costs, Refunds, Disputes and Support cases—not from manually entered dashboard numbers.</p></div><Link className="action-link" href="/admin">Overview</Link></header>{access.mode==="demo"&&<p className="prototype-warning">Preview mode. The real scorecard function is already installed in the MVP v3 database.</p>}<section className="dashboard-section"><form method="get" style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}><div><label className="field-label" htmlFor="days">Reporting window</label><select id="days" name="days" defaultValue={String(days)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="45">Last 45 days</option><option value="90">Last 90 days</option></select></div><button className="button button-secondary" type="submit">Update</button></form></section>
  <div className="metric-grid"><article className="metric-card"><span>Successful Tips</span><strong>{Number(m.successful_tip_count)}</strong><small>Pilot evidence target: ≥1,000 total</small></article><article className="metric-card"><span>Active Workers</span><strong>{Number(m.active_worker_count)}</strong><small>Workers with completed Tips</small></article><article className="metric-card"><span>Participating Venues</span><strong>{Number(m.participating_venue_count)}</strong></article><article className="metric-card"><span>Average Tip</span><strong>{formatZar(Number(m.average_gratuity_cents))}</strong></article></div>
  <div className="admin-grid"><section className="dashboard-section"><h2>Commercial evidence</h2><div className="money-breakdown"><div className="money-row"><span>Gross gratuity value</span><strong>{formatZar(Number(m.gross_gratuity_cents))}</strong></div><div className="money-row"><span>SwiftTip gross revenue</span><strong>{formatZar(Number(m.swifttip_gross_revenue_cents))}</strong></div><div className="money-row"><span>Recorded direct provider cost</span><strong>− {formatZar(Number(m.provider_cost_cents))}</strong></div><div className="money-row total"><span>Transaction contribution</span><strong>{formatZar(Number(m.contribution_cents))}</strong></div></div><div className="list-row"><div><strong>Average contribution / Tip</strong><div className="meta">Internal target ≥R1.50; stronger ≥R2.50</div></div><div>{formatZar(Number(m.average_contribution_cents))} {threshold(Number(m.average_contribution_cents),150)}</div></div><div className="list-row"><div><strong>Contribution / active Worker</strong><div className="meta">Evidence target R100; strong R150+</div></div><div>{formatZar(Number(m.contribution_per_active_worker_cents))} {threshold(Number(m.contribution_per_active_worker_cents),10000)}</div></div><div className="list-row"><strong>Transactions / active Worker</strong><span>{Number(m.transactions_per_active_worker).toFixed(2)}</span></div></section>
  <section className="dashboard-section"><h2>Operational quality</h2><div className="list-row"><div><strong>Settlement success</strong><div className="meta">Target ≥98%</div></div><div>{pct(Number(m.settlement_success_rate_pct))} {m.settlement_record_count?threshold(Number(m.settlement_success_rate_pct),98):<span className="status-chip warning">No data</span>}</div></div><div className="list-row"><div><strong>Refund rate</strong><div className="meta">Warning above 2%</div></div><div>{pct(Number(m.refund_rate_pct))} {threshold(Number(m.refund_rate_pct),2,"max")}</div></div><div className="list-row"><div><strong>Dispute rate</strong><div className="meta">Warning at 0.5%+</div></div><div>{pct(Number(m.dispute_rate_pct))} {threshold(Number(m.dispute_rate_pct),0.49,"max")}</div></div><div className="list-row"><div><strong>Support cases / 100 Tips</strong><div className="meta">Target below 5</div></div><div>{Number(m.support_cases_per_100_tips).toFixed(2)} {threshold(Number(m.support_cases_per_100_tips),4.99,"max")}</div></div></section></div>
  <section className="trust-card"><span className="trust-icon">✓</span><div><strong>No vanity pass/fail</strong><p>Zero-volume periods do not prove the pilot works. The scorecard becomes decision evidence only after real volume, real Settlements and enough observation time.</p></div></section></main>;
}
