import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdminRole } from "@/lib/access";
import { calculateTipPricing, formatZar, type PricingConfig } from "@/lib/money";
import { createSupabaseServerClient } from "@/infrastructure/supabase/server";
import { approvePricing, recordPricingReview, returnPricingToDraft, submitPricingForReview, updatePricingDraft } from "../actions";

type Pricing={pricing_id:string;version_code:string;pricing_status:string;review_status:string;review_notes:string|null;commercial_blockers:string[];effective_from:string|null;effective_until:string|null;worker_fee_bps:number;customer_fixed_fee_cents:number;customer_fee_bps:number;customer_fee_cap_cents:number|null;minimum_gratuity_cents:number;maximum_gratuity_cents:number;high_value_threshold_cents:number;currency:string;submitted_for_review_at:string|null;reviewed_at:string|null;approved_at:string|null;created_at:string;updated_at:string};

const inputStyle={width:"100%",padding:14,borderRadius:14,border:"1px solid var(--border)"};

export default async function PricingDetailPage({params,searchParams}:{params:Promise<{pricingVersionId:string}>;searchParams:Promise<{error?:string;saved?:string;submitted?:string;reviewed?:string;draft?:string;approved?:string}>}){
  const access=await requireAdminRole(["operations_admin","finance_admin","super_admin"]);
  const {pricingVersionId}=await params;
  const q=await searchParams;
  let pricing:Pricing|null=null;
  if(access.mode==="live"){
    const supabase=await createSupabaseServerClient();
    const result=await supabase.rpc("admin_get_pricing_version",{p_pricing_version_id:pricingVersionId});
    pricing=((result.data??[]) as Pricing[])[0]??null;
  }
  if(!pricing&&access.mode==="live")notFound();
  if(!pricing)pricing={pricing_id:pricingVersionId,version_code:"v3-working-001",pricing_status:"draft",review_status:"draft",review_notes:"Working figures only.",commercial_blockers:["Example commercial blocker"],effective_from:null,effective_until:null,worker_fee_bps:500,customer_fixed_fee_cents:100,customer_fee_bps:300,customer_fee_cap_cents:500,minimum_gratuity_cents:500,maximum_gratuity_cents:50000,high_value_threshold_cents:20000,currency:"ZAR",submitted_for_review_at:null,reviewed_at:null,approved_at:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const blockers=Array.isArray(pricing.commercial_blockers)?pricing.commercial_blockers:[];
  const pricingConfig:PricingConfig={workerFeeBps:Number(pricing.worker_fee_bps),customerFixedFeeCents:Number(pricing.customer_fixed_fee_cents),customerFeeBps:Number(pricing.customer_fee_bps),customerFeeCapCents:pricing.customer_fee_cap_cents==null?null:Number(pricing.customer_fee_cap_cents),minimumGratuityCents:Number(pricing.minimum_gratuity_cents),maximumGratuityCents:Number(pricing.maximum_gratuity_cents)};
  const scenarioAmounts=[pricingConfig.minimumGratuityCents,1000,2000,5000,10000,Number(pricing.high_value_threshold_cents),pricingConfig.maximumGratuityCents].filter((value,index,all)=>value>=pricingConfig.minimumGratuityCents&&value<=pricingConfig.maximumGratuityCents&&all.indexOf(value)===index).sort((a,b)=>a-b);
  const scenarios=scenarioAmounts.map(amount=>calculateTipPricing(amount,pricingConfig));
  const financeAdmin=access.role==="finance_admin"||access.role==="super_admin";
  const superAdmin=access.role==="super_admin";
  return <main className="dashboard-shell">
    <header className="dashboard-topbar"><div><span className="eyebrow">Pricing version</span><h1>{pricing.version_code}</h1><p className="lead">{pricing.review_status.replaceAll("_"," ")} · {pricing.pricing_status} · {pricing.currency}</p></div><Link className="action-link" href="/admin/pricing">Pricing register</Link></header>
    {access.mode==="demo"&&<p className="prototype-warning">Preview only — pricing mutations are disabled in demo mode.</p>}
    {q.error&&<p className="prototype-warning" role="alert">{q.error}</p>}
    {(q.saved||q.submitted||q.reviewed||q.draft||q.approved)&&<p className="status-chip success" role="status" style={{display:"inline-flex"}}>Pricing record updated.</p>}
    <div className="metric-grid" style={{marginTop:22}}><article className="metric-card"><span>Worker fee</span><strong>{Number(pricing.worker_fee_bps)/100}%</strong></article><article className="metric-card"><span>Customer fee</span><strong>{formatZar(Number(pricing.customer_fixed_fee_cents))} + {Number(pricing.customer_fee_bps)/100}%</strong><small>{pricing.customer_fee_cap_cents==null?"No cap recorded":`Cap ${formatZar(Number(pricing.customer_fee_cap_cents))}`}</small></article><article className="metric-card"><span>Tip range</span><strong>{formatZar(Number(pricing.minimum_gratuity_cents))}–{formatZar(Number(pricing.maximum_gratuity_cents))}</strong></article><article className="metric-card"><span>Open blockers</span><strong>{blockers.length}</strong></article></div>

    <section className="dashboard-section"><div className="section-heading"><h2>Activation boundary</h2><span className="status-chip warning">Inactive</span></div><p className="lead">These are working figures, not current charges. Approval does not set an effective date, schedule this version, activate payments, or open public Tip intake. No activation action exists on this page.</p><div className="list-row"><strong>Effective from</strong><span>{pricing.effective_from?new Date(pricing.effective_from).toLocaleString("en-ZA"):"Not set"}</span></div><div className="list-row"><strong>Charging status</strong><span>{pricing.pricing_status}</span></div></section>

    {pricing.review_status==="draft"&&<section className="dashboard-section"><h2>Edit working draft</h2><p className="lead">Values are stored in basis points and cents. Saving resets prior submission, review and approval evidence.</p>{financeAdmin&&access.mode==="live"&&<form action={updatePricingDraft} className="stack-actions"><input type="hidden" name="pricingVersionId" value={pricing.pricing_id}/><label className="field-label" htmlFor="workerFeeBps">Worker fee (basis points; 500 = 5%)</label><input style={inputStyle} id="workerFeeBps" name="workerFeeBps" type="number" min="0" max="10000" step="1" defaultValue={pricing.worker_fee_bps} required/><label className="field-label" htmlFor="customerFixedFeeCents">Customer fixed fee (cents; 100 = R1.00)</label><input style={inputStyle} id="customerFixedFeeCents" name="customerFixedFeeCents" type="number" min="0" step="1" defaultValue={pricing.customer_fixed_fee_cents} required/><label className="field-label" htmlFor="customerFeeBps">Customer percentage fee (basis points)</label><input style={inputStyle} id="customerFeeBps" name="customerFeeBps" type="number" min="0" max="10000" step="1" defaultValue={pricing.customer_fee_bps} required/><label className="field-label" htmlFor="customerFeeCapCents">Customer fee cap (cents; optional)</label><input style={inputStyle} id="customerFeeCapCents" name="customerFeeCapCents" type="number" min="0" step="1" defaultValue={pricing.customer_fee_cap_cents??""}/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><div><label className="field-label" htmlFor="minimumGratuityCents">Minimum Tip (cents)</label><input style={inputStyle} id="minimumGratuityCents" name="minimumGratuityCents" type="number" min="1" step="1" defaultValue={pricing.minimum_gratuity_cents} required/></div><div><label className="field-label" htmlFor="maximumGratuityCents">Maximum Tip (cents)</label><input style={inputStyle} id="maximumGratuityCents" name="maximumGratuityCents" type="number" min="1" step="1" defaultValue={pricing.maximum_gratuity_cents} required/></div><div><label className="field-label" htmlFor="highValueThresholdCents">High-value threshold (cents)</label><input style={inputStyle} id="highValueThresholdCents" name="highValueThresholdCents" type="number" min="1" step="1" defaultValue={pricing.high_value_threshold_cents} required/></div></div><label className="field-label" htmlFor="blockers">Commercial blockers — one per line</label><textarea style={inputStyle} id="blockers" name="blockers" rows={Math.max(9,blockers.length+1)} defaultValue={blockers.join("\n")}/><label className="field-label" htmlFor="reviewNotes">Draft notes</label><textarea style={inputStyle} id="reviewNotes" name="reviewNotes" rows={4} defaultValue={pricing.review_notes??""}/><button className="button button-primary" type="submit">Save working draft</button></form>}</section>}

    <section className="dashboard-section"><div className="section-heading"><h2>Commercial blockers</h2><span className={blockers.length?"status-chip warning":"status-chip success"}>{blockers.length?`${blockers.length} open`:"Cleared"}</span></div>{blockers.length?blockers.map((blocker,index)=><div className="list-row" key={`${blocker}-${index}`}><span>{index+1}. {blocker}</span></div>):<div className="empty-state"><strong>No blockers recorded</strong><p>This only makes formal approval possible after a recorded review; it does not activate pricing.</p></div>}</section>

    <section className="dashboard-section"><div className="section-heading"><h2>Unit-economics worksheet</h2><span className="status-chip warning">Provider costs pending</span></div><p className="lead">Deterministic scenarios from this exact draft. Gross revenue is shown before payment-provider, payout, refund, chargeback, tax and support costs; it must not be treated as contribution or profit.</p><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760}}><thead><tr><th style={{textAlign:"left",padding:10}}>Tip</th><th style={{textAlign:"right",padding:10}}>Customer fee</th><th style={{textAlign:"right",padding:10}}>Customer total</th><th style={{textAlign:"right",padding:10}}>Worker fee</th><th style={{textAlign:"right",padding:10}}>Worker net</th><th style={{textAlign:"right",padding:10}}>SwiftTip gross revenue</th></tr></thead><tbody>{scenarios.map(row=><tr key={row.grossGratuityCents} style={{borderTop:"1px solid var(--border)"}}><td style={{padding:10}}>{formatZar(row.grossGratuityCents)}</td><td style={{padding:10,textAlign:"right"}}>{formatZar(row.customerFeeCents)}</td><td style={{padding:10,textAlign:"right"}}>{formatZar(row.customerTotalCents)}</td><td style={{padding:10,textAlign:"right"}}>{formatZar(row.workerFeeCents)}</td><td style={{padding:10,textAlign:"right"}}>{formatZar(row.workerNetCents)}</td><td style={{padding:10,textAlign:"right"}}><strong>{formatZar(row.swifttipGrossRevenueCents)}</strong></td></tr>)}</tbody></table></div><div className="empty-state" style={{marginTop:16,textAlign:"left"}}><strong>Evidence still required</strong><p>Provider transaction pricing, split and payout costs, VAT/tax treatment, expected refund and chargeback loss, and support/reconciliation cost assumptions. Once recorded, contribution can be evaluated at every scenario above.</p></div></section>

    {pricing.review_status==="draft"&&financeAdmin&&access.mode==="live"&&<section className="dashboard-section"><h2>Submit for review</h2><p className="lead">Submission locks the figures. Blockers remain attached and must be addressed through a formal Super Admin review.</p><form action={submitPricingForReview} className="stack-actions"><input type="hidden" name="pricingVersionId" value={pricing.pricing_id}/><label className="field-label" htmlFor="submitReason">Submission note</label><input style={inputStyle} id="submitReason" name="reason" placeholder="Ready for controlled commercial review"/><button className="button button-secondary" type="submit">Submit for review</button></form></section>}

    {pricing.review_status==="under_review"&&<section className="dashboard-section"><h2>Formal review</h2><p className="lead">Only a Super Admin can record findings. Approval remains blocked until a review exists and every blocker is cleared.</p>{superAdmin&&access.mode==="live"&&<form action={recordPricingReview} className="stack-actions"><input type="hidden" name="pricingVersionId" value={pricing.pricing_id}/><label className="field-label" htmlFor="reviewBlockers">Remaining blockers — one per line</label><textarea style={inputStyle} id="reviewBlockers" name="blockers" rows={Math.max(7,blockers.length+1)} defaultValue={blockers.join("\n")}/><label className="field-label" htmlFor="formalReviewNotes">Formal review notes</label><textarea style={inputStyle} id="formalReviewNotes" name="reviewNotes" rows={5} minLength={3} required defaultValue={pricing.review_notes??""}/><button className="button button-secondary" type="submit">Record review</button></form>}</section>}

    {superAdmin&&access.mode==="live"&&pricing.review_status!=="draft"&&pricing.pricing_status==="draft"&&<section className="dashboard-section"><h2>Return to working draft</h2><form action={returnPricingToDraft} className="stack-actions"><input type="hidden" name="pricingVersionId" value={pricing.pricing_id}/><label className="field-label" htmlFor="returnReason">Reason</label><input style={inputStyle} id="returnReason" name="reason" required minLength={3}/><button className="button button-secondary" type="submit">Return to draft</button></form></section>}

    {superAdmin&&access.mode==="live"&&pricing.review_status==="under_review"&&<section className="dashboard-section"><h2>Approve figures</h2><p className="lead">Approval requires a recorded review and zero blockers. It still leaves the pricing version inactive and without an effective date.</p><form action={approvePricing} className="stack-actions"><input type="hidden" name="pricingVersionId" value={pricing.pricing_id}/><label className="field-label" htmlFor="approvalReason">Approval basis</label><input style={inputStyle} id="approvalReason" name="reason" required minLength={3}/><button className="button button-primary" type="submit" disabled={blockers.length>0||!pricing.reviewed_at}>Approve — do not activate</button></form></section>}

    <section className="dashboard-section"><h2>Review history</h2><div className="list-row"><strong>Submitted</strong><span>{pricing.submitted_for_review_at?new Date(pricing.submitted_for_review_at).toLocaleString("en-ZA"):"Not submitted"}</span></div><div className="list-row"><strong>Reviewed</strong><span>{pricing.reviewed_at?new Date(pricing.reviewed_at).toLocaleString("en-ZA"):"Not reviewed"}</span></div><div className="list-row"><strong>Approved</strong><span>{pricing.approved_at?new Date(pricing.approved_at).toLocaleString("en-ZA"):"Not approved"}</span></div>{pricing.review_notes&&<div className="empty-state" style={{marginTop:14,textAlign:"left"}}><strong>Review notes</strong><p>{pricing.review_notes}</p></div>}</section>
  </main>;
}
