"use client";

import { useMemo, useState } from "react";
import { calculateTipPricing, estimateContribution, formatZar, type DirectCostAssumptions, type PricingConfig } from "@/lib/money";

const fieldStyle={width:"100%",padding:12,borderRadius:12,border:"1px solid var(--border)"};
const initial:DirectCostAssumptions={providerVariableBps:0,providerFixedCents:0,splitCostCents:0,allocatedPayoutCostCents:0,refundChargebackReserveBps:0,supportReconciliationCostCents:0};

export function PricingEconomicsWorksheet({config,amounts}:{config:PricingConfig;amounts:number[]}){
  const [costs,setCosts]=useState(initial);
  const update=(key:keyof DirectCostAssumptions,value:string)=>setCosts(current=>({...current,[key]:Math.max(0,Math.round(Number(value)||0))}));
  const rows=useMemo(()=>amounts.map(amount=>{const pricing=calculateTipPricing(amount,config);return {pricing,estimate:estimateContribution(pricing,costs)};}),[amounts,config,costs]);
  const hasCosts=Object.values(costs).some(Boolean);
  return <section className="dashboard-section"><div className="section-heading"><h2>Provider-cost contribution model</h2><span className={hasCosts?"status-chip warning":"status-chip neutral"}>{hasCosts?"Working assumptions":"Awaiting inputs"}</span></div><p className="lead">Enter quoted costs in basis points and cents. This browser-only worksheet does not save, approve or activate pricing. Zero means “not supplied”, not “free”.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}><Field label="Provider variable fee (bps)" value={costs.providerVariableBps} onChange={v=>update("providerVariableBps",v)}/><Field label="Provider fixed fee (cents)" value={costs.providerFixedCents} onChange={v=>update("providerFixedCents",v)}/><Field label="Split cost (cents)" value={costs.splitCostCents} onChange={v=>update("splitCostCents",v)}/><Field label="Allocated payout cost (cents)" value={costs.allocatedPayoutCostCents} onChange={v=>update("allocatedPayoutCostCents",v)}/><Field label="Refund/chargeback reserve (bps)" value={costs.refundChargebackReserveBps} onChange={v=>update("refundChargebackReserveBps",v)}/><Field label="Support/reconciliation (cents)" value={costs.supportReconciliationCostCents} onChange={v=>update("supportReconciliationCostCents",v)}/></div><div style={{overflowX:"auto",marginTop:18}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760}}><thead><tr><th style={{textAlign:"left",padding:10}}>Tip</th><th style={{textAlign:"right",padding:10}}>Gross revenue</th><th style={{textAlign:"right",padding:10}}>Estimated direct cost</th><th style={{textAlign:"right",padding:10}}>Contribution</th><th style={{textAlign:"right",padding:10}}>Margin</th><th style={{textAlign:"left",padding:10}}>Result</th></tr></thead><tbody>{rows.map(({pricing,estimate})=><tr key={pricing.grossGratuityCents} style={{borderTop:"1px solid var(--border)"}}><td style={{padding:10}}>{formatZar(pricing.grossGratuityCents)}</td><td style={{padding:10,textAlign:"right"}}>{formatZar(pricing.swifttipGrossRevenueCents)}</td><td style={{padding:10,textAlign:"right"}}>{formatZar(estimate.totalDirectCostCents)}</td><td style={{padding:10,textAlign:"right",color:estimate.contributionCents<0?"var(--danger)":undefined}}><strong>{formatZar(estimate.contributionCents)}</strong></td><td style={{padding:10,textAlign:"right"}}>{estimate.contributionMarginBps==null?"—":`${(estimate.contributionMarginBps/100).toFixed(1)}%`}</td><td style={{padding:10}}><span className={estimate.contributionCents<0?"status-chip danger":"status-chip success"}>{estimate.contributionCents<0?"Loss":"Positive"}</span></td></tr>)}</tbody></table></div><p className="prototype-warning" style={{marginTop:16}}>Commercial evidence remains blocked until every input is supported by an approved provider quote or documented Finance assumption.</p></section>;
}

function Field({label,value,onChange}:{label:string;value:number;onChange:(value:string)=>void}){return <label className="field-label">{label}<input style={fieldStyle} type="number" min="0" max="10000" step="1" value={value} onChange={event=>onChange(event.target.value)}/></label>;}
