import Link from "next/link";
import { requireAdminRole } from "@/lib/access";
import { createSupabaseServerClient } from "@/infrastructure/supabase/server";
import { createVenue, approveVenue } from "./actions";

type Venue={venue_id:string;trading_name:string;branch_name:string|null;venue_type:string;public_location_label:string|null;venue_status:string;active_member_count:number;verified_worker_count:number;pending_worker_count:number;created_at:string};

export default async function AdminVenuesPage({searchParams}:{searchParams:Promise<{error?:string;created?:string;approved?:string}>}){
  const access=await requireAdminRole(["operations_admin","super_admin"]);
  const params=await searchParams;
  let rows:Venue[]=[];
  if(access.mode==="live"){
    const supabase=await createSupabaseServerClient();
    const {data}=await supabase.rpc("admin_get_venues",{p_status:null});
    rows=(data??[]) as Venue[];
  }
  return <main className="dashboard-shell"><header className="dashboard-topbar"><div><span className="eyebrow">Venue operations</span><h1>Venue register</h1><p className="lead">SwiftTip creates and approves participating Venues. Venue users cannot self-authorise a location.</p></div><Link className="action-link" href="/admin">Overview</Link></header>
  {access.mode==="demo"&&<p className="prototype-warning">Preview mode. Venue mutations become available only after the live Supabase connection is attached.</p>}
  {params.error&&<p className="prototype-warning" role="alert">{params.error}</p>}{params.created&&<p className="status-chip success" style={{display:"inline-flex"}}>Venue created for review</p>}{params.approved&&<p className="status-chip success" style={{display:"inline-flex"}}>Venue approved</p>}
  <div className="admin-grid"><section className="dashboard-section"><h2>Add Venue</h2><form action={createVenue} className="stack-actions" style={{marginTop:18}}><label className="field-label" htmlFor="tradingName">Trading name</label><div className="custom-field"><input id="tradingName" name="tradingName" placeholder="Example Service Station" required/></div><label className="field-label" htmlFor="branchName">Branch / site name</label><div className="custom-field"><input id="branchName" name="branchName" placeholder="Midrand"/></div><label className="field-label" htmlFor="venueType">Venue type</label><select id="venueType" name="venueType" defaultValue="fuel_station"><option value="fuel_station">Fuel station</option><option value="car_wash">Car wash</option><option value="valet">Valet</option><option value="hotel">Hotel</option><option value="restaurant">Restaurant</option><option value="other">Other</option></select><label className="field-label" htmlFor="city">City</label><div className="custom-field"><input id="city" name="city"/></div><label className="field-label" htmlFor="province">Province</label><div className="custom-field"><input id="province" name="province" placeholder="Gauteng"/></div><label className="field-label" htmlFor="locationLabel">Public location label</label><div className="custom-field"><input id="locationLabel" name="locationLabel" placeholder="Midrand"/></div><button className="button button-primary" type="submit">Create Venue for review</button></form></section>
  <section className="dashboard-section"><h2>Operating boundary</h2><p className="lead">Venue approval means SwiftTip recognises the participating location. It does not make the Venue merchant of record, grant Settlement authority, or create a payroll relationship.</p><div className="list-row"><strong>Venue pays mandatory subscription</strong><span>No</span></div><div className="list-row"><strong>Venue sees Worker bank/KYC</strong><span>No</span></div><div className="list-row"><strong>Venue controls Worker Settlement</strong><span>No</span></div><div className="list-row"><strong>Venue confirms Worker relationship</strong><span>Yes</span></div></section></div>
  <section className="dashboard-section"><div className="section-heading"><h2>Registered Venues</h2><span className="meta">{rows.length}</span></div>{rows.length?rows.map(v=><div className="list-row" key={v.venue_id}><div><strong>{v.branch_name||v.trading_name}</strong><div className="meta">{v.trading_name} · {v.venue_type.replaceAll("_"," ")}{v.public_location_label?` · ${v.public_location_label}`:""} · {Number(v.verified_worker_count)} verified Workers · {Number(v.pending_worker_count)} pending</div></div><div style={{display:"flex",alignItems:"center",gap:10}}><span className={v.venue_status==="active"?"status-chip success":"status-chip warning"}>{v.venue_status.replaceAll("_"," ")}</span>{["draft","pending_review","suspended"].includes(v.venue_status)&&access.mode==="live"&&<form action={approveVenue}><input type="hidden" name="venueId" value={v.venue_id}/><button className="button button-secondary" type="submit">Approve</button></form>}</div></div>):<div className="empty-state"><strong>No Venues yet</strong><p>The register is ready for the first pilot locations.</p></div>}</section></main>;
}
