import Link from "next/link";
import { AppMark } from "@/components/AppMark";
import { BottomNav } from "@/components/BottomNav";
import { requireWorkerSurface } from "@/lib/access";

export default async function WorkerPage(){
  const access=await requireWorkerSurface();
  const tx=[['R50.00','Today · 10:42','Processing'],['R20.00','Today · 09:15','Settled'],['R100.00','Yesterday · 17:09','Settled']];
  return <main className="mobile-app-shell"><div className="app-page"><header className="topbar"><div className="brand-lockup"><AppMark size={38}/><strong>SwiftTip</strong></div><span className="status-chip success">✓ Active</span></header>{access.mode==='demo'&&<p className="prototype-warning">Preview data only — live worker data requires the new MVP v3 database.</p>}<section className="dashboard-title"><span className="eyebrow">Worker</span><h1>Good morning, Thando 👋</h1><p className="lead">Ready to receive tips at Riverside Service Station.</p></section><div className="metric-grid" style={{marginTop:22}}><article className="metric-card"><span>Today's gross tips</span><strong>R180.00</strong><small>5 tips</small></article><article className="metric-card"><span>This month</span><strong>R2,450.00</strong><small>Gross tips</small></article><article className="metric-card"><span>Processing</span><strong>R175.00</strong><small>4 tips</small></article><article className="metric-card"><span>Settled</span><strong>R2,137.50</strong><small>This month</small></article></div><section className="dashboard-section"><div className="section-heading"><h2>Recent tips</h2><Link className="action-link" href="/worker">View all</Link></div>{tx.map(([amount,time,state])=><div className="list-row" key={amount+time}><div><strong>{amount}</strong><div className="meta">{time}</div></div><span className={state==='Settled'?'status-chip success':'status-chip warning'}>{state}</span></div>)}</section><section className="dashboard-section"><h2>Your QR</h2><p className="lead">Your venue-context QR is ready. It never contains banking details or a wallet balance.</p><Link className="button button-primary" href="/tip/T4K8P" style={{marginTop:15}}>Preview customer flow</Link></section></div><BottomNav active="worker"/></main>;
}
