import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdminRole } from "@/lib/access";
import { createSupabaseServerClient } from "@/infrastructure/supabase/server";
import { approveLegalDocument, recordLegalReview, returnLegalToDraft, submitLegalForReview, updateLegalDraft } from "../actions";

type LegalDoc={terms_version_id:string;terms_type:string;version_code:string;title:string;content_body:string;content_format:string;content_hash:string;review_status:string;review_notes:string|null;legal_blockers:string[];published_at:string|null;effective_from:string;submitted_for_review_at:string|null;reviewed_at:string|null;approved_at:string|null;updated_at:string;source_repository:string|null;source_path:string|null;source_blob_sha:string|null;source_bytes:number|null;source_synced_at:string|null};
const labels:Record<string,string>={worker_terms:"Worker Terms",venue_terms:"Venue Terms",customer_transaction_terms:"Customer Transaction Terms",privacy_notice:"Privacy Notice"};

function sourceUrl(doc:LegalDoc){
  if(!doc.source_repository?.match(/^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/)||!doc.source_path?.match(/^[a-zA-Z0-9_./-]+$/))return null;
  return `https://github.com/${doc.source_repository}/blob/mvp-v3-greenfield-build/${doc.source_path}`;
}

export default async function LegalDetailPage({params,searchParams}:{params:Promise<{termsVersionId:string}>;searchParams:Promise<{error?:string;saved?:string;submitted?:string;reviewed?:string;draft?:string;approved?:string}>}){
  const access=await requireAdminRole(["operations_admin","super_admin"]);
  const {termsVersionId}=await params;
  const q=await searchParams;
  let doc:LegalDoc|null=null;
  if(access.mode==="live"){
    const supabase=await createSupabaseServerClient();
    const result=await supabase.rpc("admin_get_legal_document",{p_terms_version_id:termsVersionId});
    doc=((result.data??[]) as LegalDoc[])[0]??null;
  }
  if(!doc&&access.mode==="live")notFound();
  if(!doc)doc={terms_version_id:termsVersionId,terms_type:"worker_terms",version_code:"v0.1-draft",title:"SwiftTip Worker Terms — Draft v0.1",content_body:"Preview mode. Legal content is loaded from the canonical database in live mode.",content_format:"markdown",content_hash:"preview",review_status:"draft",review_notes:null,legal_blockers:["Example blocker"],published_at:null,effective_from:"2099-01-01T00:00:00Z",submitted_for_review_at:null,reviewed_at:null,approved_at:null,updated_at:new Date().toISOString(),source_repository:null,source_path:null,source_blob_sha:null,source_bytes:null,source_synced_at:null};
  const blockers=Array.isArray(doc.legal_blockers)?doc.legal_blockers:[];
  const superAdmin=access.role==="super_admin";
  const repositorySourceUrl=sourceUrl(doc);
  return <main className="dashboard-shell">
    <header className="dashboard-topbar"><div><span className="eyebrow">{labels[doc.terms_type]??doc.terms_type}</span><h1>{doc.title}</h1><p className="lead">Version {doc.version_code} · {doc.review_status.replaceAll("_"," ")} · {doc.published_at?"published":"unpublished"}</p></div><Link className="action-link" href="/admin/legal">Legal register</Link></header>
    {access.mode==="demo"&&<p className="prototype-warning">Preview only — legal mutations are disabled in demo mode.</p>}
    {q.error&&<p className="prototype-warning" role="alert">{q.error}</p>}
    {(q.saved||q.submitted||q.reviewed||q.draft||q.approved)&&<p className="status-chip success" role="status" style={{display:"inline-flex"}}>Legal record updated.</p>}
    <div className="metric-grid" style={{marginTop:22}}><article className="metric-card"><span>Status</span><strong>{doc.review_status.replaceAll("_"," ")}</strong></article><article className="metric-card"><span>Open blockers</span><strong>{blockers.length}</strong></article><article className="metric-card"><span>Published</span><strong>{doc.published_at?"Yes":"No"}</strong></article><article className="metric-card"><span>Content hash</span><strong style={{fontSize:14,wordBreak:"break-all"}}>{doc.content_hash.slice(0,16)}…</strong></article></div>

    <section className="dashboard-section"><div className="section-heading"><h2>Publication boundary</h2><span className="status-chip warning">No publish action</span></div><p className="lead">The 2099 effective date is a draft safety placeholder. Approval here does not make this document effective, does not set <code>published_at</code>, and does not satisfy the live-money gate.</p></section>

    <section className="dashboard-section"><div className="section-heading"><h2>Controlled source</h2><span className={doc.source_synced_at?"status-chip success":"status-chip warning"}>{doc.source_synced_at?"Fingerprint recorded":"Source not recorded"}</span></div><p className="lead">Repository provenance lets a reviewer compare this database draft with the controlled file. The SHA-256 above binds the database content; the Git blob fingerprint identifies the source file captured at synchronisation.</p>{doc.source_repository&&doc.source_path?<><div className="list-row"><strong>Repository</strong><span>{doc.source_repository}</span></div><div className="list-row"><strong>Source path</strong><span style={{overflowWrap:"anywhere"}}>{doc.source_path}</span></div><div className="list-row"><strong>Git blob SHA</strong><span style={{overflowWrap:"anywhere"}}>{doc.source_blob_sha??"Not recorded"}</span></div><div className="list-row"><strong>Source bytes</strong><span>{doc.source_bytes?.toLocaleString("en-ZA")??"Not recorded"}</span></div><div className="list-row"><strong>Last synchronised</strong><span>{doc.source_synced_at?new Date(doc.source_synced_at).toLocaleString("en-ZA"):"Not recorded"}</span></div>{repositorySourceUrl&&<a className="action-link" href={repositorySourceUrl} target="_blank" rel="noreferrer">Open controlled source ↗</a>}</>:<div className="empty-state"><strong>No repository source attached</strong><p>Do not submit this version for review until its controlled source has been synchronised.</p></div>}</section>

    {doc.review_status==="draft"&&<section className="dashboard-section"><h2>Edit draft</h2><p className="lead">Editing recalculates the SHA-256 content hash. Once submitted for review, content is locked until a Super Admin returns it to draft.</p>{access.mode==="live"&&<form action={updateLegalDraft} className="stack-actions"><input type="hidden" name="termsVersionId" value={doc.terms_version_id}/><label className="field-label" htmlFor="title">Title</label><div className="custom-field"><input id="title" name="title" defaultValue={doc.title} required/></div><label className="field-label" htmlFor="contentBody">Markdown content</label><textarea id="contentBody" name="contentBody" defaultValue={doc.content_body} required rows={34} style={{width:"100%",fontFamily:"ui-monospace, SFMono-Regular, Menlo, monospace",fontSize:13,lineHeight:1.5,padding:16,borderRadius:14,border:"1px solid var(--border)"}}/><label className="field-label" htmlFor="blockers">Publication blockers — one per line</label><textarea id="blockers" name="blockers" defaultValue={blockers.join("\n")} rows={Math.max(5,blockers.length+1)} style={{width:"100%",padding:14,borderRadius:14,border:"1px solid var(--border)"}}/><label className="field-label" htmlFor="reviewNotes">Draft notes</label><textarea id="reviewNotes" name="reviewNotes" defaultValue={doc.review_notes??""} rows={4} style={{width:"100%",padding:14,borderRadius:14,border:"1px solid var(--border)"}}/><button className="button button-primary" type="submit">Save draft</button></form>}</section>}

    <section className="dashboard-section"><div className="section-heading"><h2>Blockers</h2><span className={blockers.length?"status-chip warning":"status-chip success"}>{blockers.length?`${blockers.length} open`:"Cleared"}</span></div>{blockers.length?blockers.map((b,i)=><div className="list-row" key={`${b}-${i}`}><span>{i+1}. {b}</span></div>):<div className="empty-state"><strong>No blockers recorded</strong><p>This does not publish the document; it only makes approval technically possible after review.</p></div>}</section>

    {doc.review_status==="draft"&&access.mode==="live"&&<section className="dashboard-section"><h2>Submit for review</h2><p className="lead">Submission locks content. Existing blockers travel with the review package and can only be cleared through a recorded review.</p><form action={submitLegalForReview} className="stack-actions"><input type="hidden" name="termsVersionId" value={doc.terms_version_id}/><label className="field-label" htmlFor="submitReason">Submission note</label><div className="custom-field"><input id="submitReason" name="reason" placeholder="Ready for legal/commercial review"/></div><button className="button button-secondary" type="submit">Submit for review</button></form></section>}

    {doc.review_status==="under_review"&&<section className="dashboard-section"><h2>Review record</h2><p className="lead">Only a Super Admin can record formal review findings or approval. Approval is blocked while any blocker remains.</p>{superAdmin&&access.mode==="live"&&<form action={recordLegalReview} className="stack-actions"><input type="hidden" name="termsVersionId" value={doc.terms_version_id}/><label className="field-label" htmlFor="reviewBlockers">Remaining blockers — one per line</label><textarea id="reviewBlockers" name="blockers" defaultValue={blockers.join("\n")} rows={Math.max(5,blockers.length+1)} style={{width:"100%",padding:14,borderRadius:14,border:"1px solid var(--border)"}}/><label className="field-label" htmlFor="formalReviewNotes">Formal review notes</label><textarea id="formalReviewNotes" name="reviewNotes" defaultValue={doc.review_notes??""} required minLength={3} rows={5} style={{width:"100%",padding:14,borderRadius:14,border:"1px solid var(--border)"}}/><button className="button button-secondary" type="submit">Record review</button></form>}</section>}

    {superAdmin&&access.mode==="live"&&doc.review_status!=="draft"&&<section className="dashboard-section"><h2>Return to draft</h2><p className="lead">Use this when content must change. Published versions can never be returned to draft.</p><form action={returnLegalToDraft} className="stack-actions"><input type="hidden" name="termsVersionId" value={doc.terms_version_id}/><label className="field-label" htmlFor="returnReason">Reason</label><div className="custom-field"><input id="returnReason" name="reason" required minLength={3}/></div><button className="button button-secondary" type="submit">Return to draft</button></form></section>}

    {superAdmin&&access.mode==="live"&&doc.review_status==="under_review"&&<section className="dashboard-section"><h2>Approve draft</h2><p className="lead">Approval is allowed only after a formal review and only when the blocker list is empty. It still does not publish or activate the document.</p><form action={approveLegalDocument} className="stack-actions"><input type="hidden" name="termsVersionId" value={doc.terms_version_id}/><label className="field-label" htmlFor="approvalReason">Approval basis</label><div className="custom-field"><input id="approvalReason" name="reason" required minLength={3} placeholder="Reviewed and approved for controlled publication step"/></div><button className="button button-primary" type="submit" disabled={blockers.length>0}>Approve — not publish</button></form></section>}

    <section className="dashboard-section"><h2>Review history</h2><div className="list-row"><strong>Submitted</strong><span>{doc.submitted_for_review_at?new Date(doc.submitted_for_review_at).toLocaleString("en-ZA"):"Not submitted"}</span></div><div className="list-row"><strong>Reviewed</strong><span>{doc.reviewed_at?new Date(doc.reviewed_at).toLocaleString("en-ZA"):"Not reviewed"}</span></div><div className="list-row"><strong>Approved</strong><span>{doc.approved_at?new Date(doc.approved_at).toLocaleString("en-ZA"):"Not approved"}</span></div>{doc.review_notes&&<div className="empty-state" style={{marginTop:14,textAlign:"left"}}><strong>Review notes</strong><p>{doc.review_notes}</p></div>}</section>
  </main>;
}
